//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Category
    {
        [Key]
        public int CategoryId { get; set; }
        [Display(Name = "Category Name")]
        [Required]
        public string CategoryName { get; set; }
        [Display(Name = "Category Description")]
        [Required]
        public string CategoryDescription { get; set; }
        public virtual ICollection<Game> Games { get; set; }
        [Display(Name = "DateAdded")]
        public DateTime DateAdded { get; set; } 
    }
}
