//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore
{
    using GameStore.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Game
    {
        [Key]
        public int GameId { get; set; }
        public string Name { get; set; }
        public string Filename { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Update> Updates { get; set; }
        public virtual ICollection<Download> Downloads { get; set; }
        public virtual int GameAge => (int)(DateTime.Now - (ReleaseDate ?? DateTime.Now)).TotalDays / 365;
    }
}
